In [1]:
# Dependencies
import pandas as pd
from pathlib import Path

In [2]:
#Read in csv files
MHS_2015 = Path('MHS_2015totals.csv')
MHS_2016 = Path('MHS_2016totals.csv')
MHS_2017 = Path('MHS_2017totals.csv')

df_2015 = pd.read_csv(MHS_2015)
df_2016 = pd.read_csv(MHS_2016)
df_2017 = pd.read_csv(MHS_2017)

In [3]:
df_2015.columns

Index(['Player', 'Ace', 'Err', 'Srv', 'ServeQuality', 'RcvAvg', 'RcvCount',
       'Blk', 'Dig', 'Err.1', 'Kil', 'Err.2', 'Att', '%', 'IPE', 'AttRate',
       'Assists', 'BHE', 'BlocksErrors', 'RcvCnt', 'RcvErr', 'ServingPoints',
       'AssistAttempts', 'RcvQualTot', 'SrvQualTot', 'GamesPlayed'],
      dtype='object')

In [4]:
#Drop the columns/rows not needed
clean_2015 = df_2015[['Player', 'Ace', 'Err', 'Srv', 'RcvCount', 'Dig', 'Err.1', 'Kil', 'Err.2', 'Att', 'RcvErr',
        'RcvQualTot', 'GamesPlayed']]

clean_2015 = clean_2015.dropna(how='any')
clean_2015

,Player,Ace,Err,Srv,RcvCount,Dig,Err.1,Kil,Err.2,Att,RcvErr,RcvQualTot,GamesPlayed
0,Caitlin Keefe,10,10,181,355,205,42.0,272.0,86.0,746.0,29.0,734.0,89.0
1,Cami Carfino,15,12,142,134,90,34.0,7.0,3.0,32.0,22.0,252.0,61.0
2,Charlie Robinson,9,20,123,8,41,10.0,232.0,71.0,534.0,2.0,11.0,102.0
3,Devon Newberry,16,28,304,587,285,103.0,299.0,137.0,882.0,56.0,1141.0,100.0
4,Emily Newberry,2,9,33,11,13,6.0,0.0,0.0,0.0,6.0,12.0,23.0
5,Emma Moffet,0,1,12,4,18,5.0,88.0,47.0,249.0,3.0,1.0,96.0
6,Haley Kortekaas,4,3,29,0,21,4.0,1.0,1.0,3.0,0.0,0.0,19.0
7,Hanna Klein,23,21,342,1,218,61.0,52.0,11.0,145.0,0.0,3.0,99.0
8,Jennie Burke,0,0,0,10,46,22.0,83.0,40.0,285.0,4.0,11.0,84.0
9,Lauren Douglas,4,4,76,33,59,24.0,0.0,0.0,1.0,1.0,67.0,33.0
10,Lauren Gurbach,14,22,242,449,285,135.0,0.0,0.0,0.0,33.0,868.0,86.0
11,Lexie Freund,0,0,0,0,0,0.0,1.0,0.0,3.0,0.0,0.0,6.0
12,Linea Fuller,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
13,Megan Carroll,4,1,13,2,6,0.0,0.0,0.0,0.0,0.0,4.0,4.0
14,Michaela Keefe,0,0,3,21,27,7.0,56.0,13.0,126.0,6.0,28.0,21.0
15,Morgan Williams,34,37,302,94,118,35.0,10.0,13.0,52.0,12.0,169.0,88.0
16,Ruby Lightbourn,0,0,0,6,6,1.0,7.0,6.0,32.0,0.0,11.0,9.0
17,Sarah Allman,2,0,10,10,5,3.0,0.0,0.0,1.0,1.0,24.0,8.0
18,Sarah McRoskey,22,24,285,12,137,62.0,0.0,0.0,1.0,3.0,24.0,90.0
19,Yurika Boyd,1,4,30,61,21,19.0,0.0,0.0,1.0,6.0,118.0,17.0

In [5]:
clean_2016 = df_2016[['Player', 'Ace', 'Err', 'Srv', 'RcvCount', 'Dig', 'Err.1', 'Kil', 'Err.2', 'Att', 'RcvErr',
        'RcvQualTot', 'GamesPlayed']]

clean_2016 = clean_2016.dropna(how='any')
clean_2016

,Player,Ace,Err,Srv,RcvCount,Dig,Err.1,Kil,Err.2,Att,RcvErr,RcvQualTot,GamesPlayed
0,Amara Aimufua,0,0,0,1,0,2.0,2.0,0.0,3.0,0.0,3.0,2.0
1,Cami Carfino,36,60,457,681,329,54.0,260.0,100.0,746.0,55.0,1375.0,124.0
2,Devon Newberry,45,54,463,642,376,101.0,407.0,168.0,991.0,49.0,1357.0,125.0
3,Emery Beacom,1,1,13,2,12,2.0,57.0,25.0,182.0,2.0,0.0,70.0
4,Emma Moffet,0,2,13,8,19,4.0,210.0,58.0,493.0,5.0,5.0,127.0
5,Grace Frohling,63,54,501,4,183,97.0,316.0,85.0,759.0,0.0,9.0,128.0
6,Haley Kortekaas,17,29,283,2,196,53.0,5.0,0.0,12.0,2.0,0.0,119.0
7,Hareena Johnson,1,0,6,14,2,0.0,4.0,9.0,21.0,4.0,17.0,13.0
8,Jennie Burke,16,20,154,20,87,32.0,207.0,84.0,539.0,3.0,32.0,127.0
9,Lauren Douglas,7,16,150,52,38,15.0,0.0,0.0,1.0,6.0,89.0,54.0
10,Lexie Freund,14,14,129,0,30,16.0,1.0,0.0,4.0,0.0,0.0,45.0
11,Maddy McMahon,0,0,0,0,0,0.0,1.0,0.0,3.0,0.0,0.0,1.0
12,Mitzi Novicic,15,8,119,6,25,5.0,53.0,23.0,167.0,4.0,2.0,84.0
13,Ruby Lightbourn,5,10,36,72,29,13.0,44.0,17.0,139.0,12.0,117.0,46.0
14,Sarah Allman,35,51,244,104,76,24.0,1.0,1.0,3.0,9.0,208.0,84.0
15,Taylor Fourtiq,20,14,206,0,30,9.0,2.0,1.0,3.0,0.0,0.0,69.0
16,Yuika Boyd,16,24,185,587,373,132.0,1.0,0.0,2.0,40.0,1226.0,121.0

In [6]:
clean_2017 = df_2017[['Player', 'Ace', 'Err', 'Srv', 'RcvCount', 'Dig', 'Err.1', 'Kil', 'Err.2', 'Att', 'RcvErr',
        'RcvQualTot', 'GamesPlayed']]

clean_2017 = clean_2017.dropna(how='any')
clean_2017

,Player,Ace,Err,Srv,RcvCount,Dig,Err.1,Kil,Err.2,Att,RcvErr,RcvQualTot,GamesPlayed
0,Addie Edwards,5,11,163,37,37,20.0,0.0,0.0,0.0,5.0,61.0,53.0
1,Alouette Jourdan,0,0,0,0,0,0.0,1.0,1.0,4.0,0.0,0.0,3.0
2,Amara Aimufua,0,0,0,10,53,31.0,172.0,73.0,407.0,2.0,18.0,101.0
3,Cami Carfino,56,39,481,810,414,97.0,56.0,42.0,177.0,61.0,1695.0,123.0
4,Caroline Altergott,23,40,225,351,108,30.0,50.0,17.0,155.0,41.0,671.0,85.0
5,Caroline Douglas,27,27,351,347,232,57.0,0.0,0.0,5.0,41.0,596.0,113.0
6,Devon Newberry,42,57,451,552,316,101.0,413.0,164.0,978.0,42.0,1195.0,132.0
7,Emery Beacom,1,0,4,12,16,8.0,166.0,83.0,460.0,2.0,22.0,122.0
8,Emma Moffet,0,2,10,8,30,5.0,249.0,74.0,532.0,4.0,8.0,111.0
9,Grace DiNapoli,3,0,12,0,0,0.0,0.0,0.0,4.0,0.0,0.0,6.0
10,Grace Frohling,49,79,418,15,219,121.0,232.0,73.0,587.0,1.0,32.0,129.0
11,Hareena Johnson,6,15,53,6,14,4.0,14.0,11.0,60.0,0.0,11.0,44.0
12,Jacqueline Kortekaas,0,5,20,0,4,3.0,0.0,0.0,0.0,0.0,0.0,12.0
13,Jennie Burke,3,2,25,55,59,23.0,142.0,54.0,383.0,10.0,95.0,102.0
14,Mitzi Novicic,4,4,54,8,28,9.0,48.0,28.0,148.0,5.0,5.0,55.0
15,Olivia Devereux,0,0,0,0,2,1.0,6.0,3.0,19.0,0.0,0.0,12.0
16,Rose Allegrette,1,1,2,0,0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
17,Sophie Globe,11,10,174,68,58,24.0,0.0,0.0,0.0,6.0,129.0,60.0
18,Taylor Fourtiq,44,28,509,3,215,68.0,20.0,1.0,33.0,2.0,3.0,128.0

In [7]:
#Merge 2015 and 2016
df_1516 = pd.merge(clean_2015, clean_2016, on = 'Player', how = 'outer')
df_1516

,Player,Ace_x,Err_x,Srv_x,RcvCount_x,Dig_x,Err.1_x,Kil_x,Err.2_x,Att_x,...,Srv_y,RcvCount_y,Dig_y,Err.1_y,Kil_y,Err.2_y,Att_y,RcvErr_y,RcvQualTot_y,GamesPlayed_y
0,Caitlin Keefe,10,10,181,355,205,42.0,272.0,86.0,746.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cami Carfino,15,12,142,134,90,34.0,7.0,3.0,32.0,...,457,681,329,54.0,260.0,100.0,746.0,55.0,1375.0,124.0
2,Charlie Robinson,9,20,123,8,41,10.0,232.0,71.0,534.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Devon Newberry,16,28,304,587,285,103.0,299.0,137.0,882.0,...,463,642,376,101.0,407.0,168.0,991.0,49.0,1357.0,125.0
4,Emily Newberry,2,9,33,11,13,6.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Emma Moffet,0,1,12,4,18,5.0,88.0,47.0,249.0,...,13,8,19,4.0,210.0,58.0,493.0,5.0,5.0,127.0
6,Haley Kortekaas,4,3,29,0,21,4.0,1.0,1.0,3.0,...,283,2,196,53.0,5.0,0.0,12.0,2.0,0.0,119.0
7,Hanna Klein,23,21,342,1,218,61.0,52.0,11.0,145.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Jennie Burke,0,0,0,10,46,22.0,83.0,40.0,285.0,...,154,20,87,32.0,207.0,84.0,539.0,3.0,32.0,127.0
9,Lauren Douglas,4,4,76,33,59,24.0,0.0,0.0,1.0,...,150,52,38,15.0,0.0,0.0,1.0,6.0,89.0,54.0
10,Lauren Gurbach,14,22,242,449,285,135.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Lexie Freund,0,0,0,0,0,0.0,1.0,0.0,3.0,...,129,0,30,16.0,1.0,0.0,4.0,0.0,0.0,45.0
12,Linea Fuller,0,0,0,0,0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Megan Carroll,4,1,13,2,6,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Michaela Keefe,0,0,3,21,27,7.0,56.0,13.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Morgan Williams,34,37,302,94,118,35.0,10.0,13.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ruby Lightbourn,0,0,0,6,6,1.0,7.0,6.0,32.0,...,36,72,29,13.0,44.0,17.0,139.0,12.0,117.0,46.0
17,Sarah Allman,2,0,10,10,5,3.0,0.0,0.0,1.0,...,244,104,76,24.0,1.0,1.0,3.0,9.0,208.0,84.0
18,Sarah McRoskey,22,24,285,12,137,62.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Yurika Boyd,1,4,30,61,21,19.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Amara Aimufua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,2.0,2.0,0.0,3.0,0.0,3.0,2.0
21,Emery Beacom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13,2,12,2.0,57.0,25.0,182.0,2.0,0.0,70.0
22,Grace Frohling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,501,4,183,97.0,316.0,85.0,759.0,0.0,9.0,128.0
23,Hareena Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,14,2,0.0,4.0,9.0,21.0,4.0,17.0,13.0
24,Maddy McMahon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0.0,1.0,0.0,3.0,0.0,0.0,1.0
25,Mitzi Novicic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,119,6,25,5.0,53.0,23.0,167.0,4.0,2.0,84.0
26,Taylor Fourtiq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,206,0,30,9.0,2.0,1.0,3.0,0.0,0.0,69.0
27,Yuika Boyd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,185,587,373,132.0,1.0,0.0,2.0,40.0,1226.0,121.0

In [21]:
#Merge in 2017
final_df = pd.merge(df_1516, clean_2017, on = 'Player', how = 'outer')
final_df

,Player,Ace_x,Err_x,Srv_x,RcvCount_x,Dig_x,Err.1_x,Kil_x,Err.2_x,Att_x,...,Srv,RcvCount,Dig,Err.1,Kil,Err.2,Att,RcvErr,RcvQualTot,GamesPlayed
0,Caitlin Keefe,10,10,181,355,205,42.0,272.0,86.0,746.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cami Carfino,15,12,142,134,90,34.0,7.0,3.0,32.0,...,481,810,414,97.0,56.0,42.0,177.0,61.0,1695.0,123.0
2,Charlie Robinson,9,20,123,8,41,10.0,232.0,71.0,534.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Devon Newberry,16,28,304,587,285,103.0,299.0,137.0,882.0,...,451,552,316,101.0,413.0,164.0,978.0,42.0,1195.0,132.0
4,Emily Newberry,2,9,33,11,13,6.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Emma Moffet,0,1,12,4,18,5.0,88.0,47.0,249.0,...,10,8,30,5.0,249.0,74.0,532.0,4.0,8.0,111.0
6,Haley Kortekaas,4,3,29,0,21,4.0,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Hanna Klein,23,21,342,1,218,61.0,52.0,11.0,145.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Jennie Burke,0,0,0,10,46,22.0,83.0,40.0,285.0,...,25,55,59,23.0,142.0,54.0,383.0,10.0,95.0,102.0
9,Lauren Douglas,4,4,76,33,59,24.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Lauren Gurbach,14,22,242,449,285,135.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Lexie Freund,0,0,0,0,0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Linea Fuller,0,0,0,0,0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Megan Carroll,4,1,13,2,6,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Michaela Keefe,0,0,3,21,27,7.0,56.0,13.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Morgan Williams,34,37,302,94,118,35.0,10.0,13.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ruby Lightbourn,0,0,0,6,6,1.0,7.0,6.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Sarah Allman,2,0,10,10,5,3.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Sarah McRoskey,22,24,285,12,137,62.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Yurika Boyd,1,4,30,61,21,19.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Amara Aimufua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,10,53,31.0,172.0,73.0,407.0,2.0,18.0,101.0
21,Emery Beacom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,12,16,8.0,166.0,83.0,460.0,2.0,22.0,122.0
22,Grace Frohling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,418,15,219,121.0,232.0,73.0,587.0,1.0,32.0,129.0
23,Hareena Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53,6,14,4.0,14.0,11.0,60.0,0.0,11.0,44.0
24,Maddy McMahon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Mitzi Novicic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54,8,28,9.0,48.0,28.0,148.0,5.0,5.0,55.0
26,Taylor Fourtiq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,509,3,215,68.0,20.0,1.0,33.0,2.0,3.0,128.0
27,Yuika Boyd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Addie Edwards,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,163,37,37,20.0,0.0,0.0,0.0,5.0,61.0,53.0
29,Alouette Jourdan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0.0,1.0,1.0,4.0,0.0,0.0,3.0
30,Caroline Altergott,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,225,351,108,30.0,50.0,17.0,155.0,41.0,671.0,85.0
31,Caroline Douglas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,351,347,232,57.0,0.0,0.0,5.0,41.0,596.0,113.0
32,Grace DiNapoli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,0,0,0.0,0.0,0.0,4.0,0.0,0.0,6.0
33,Jacqueline Kortekaas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,0,4,3.0,0.0,0.0,0.0,0.0,0.0,12.0
34,Olivia Devereux,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,2,1.0,6.0,3.0,19.0,0.0,0.0,12.0
35,Rose Allegrette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
36,Sophie Globe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,174,68,58,24.0,0.0,0.0,0.0,6.0,129.0,60.0

In [22]:
final_df.columns

Index(['Player', 'Ace_x', 'Err_x', 'Srv_x', 'RcvCount_x', 'Dig_x', 'Err.1_x',
       'Kil_x', 'Err.2_x', 'Att_x', 'RcvErr_x', 'RcvQualTot_x',
       'GamesPlayed_x', 'Ace_y', 'Err_y', 'Srv_y', 'RcvCount_y', 'Dig_y',
       'Err.1_y', 'Kil_y', 'Err.2_y', 'Att_y', 'RcvErr_y', 'RcvQualTot_y',
       'GamesPlayed_y', 'Ace', 'Err', 'Srv', 'RcvCount', 'Dig', 'Err.1', 'Kil',
       'Err.2', 'Att', 'RcvErr', 'RcvQualTot', 'GamesPlayed'],
      dtype='object')

In [23]:
final_df.dtypes

Player            object
Ace_x             object
Err_x             object
Srv_x             object
RcvCount_x        object
Dig_x             object
Err.1_x          float64
Kil_x            float64
Err.2_x          float64
Att_x            float64
RcvErr_x         float64
RcvQualTot_x     float64
GamesPlayed_x    float64
Ace_y             object
Err_y             object
Srv_y             object
RcvCount_y        object
Dig_y             object
Err.1_y          float64
Kil_y            float64
Err.2_y          float64
Att_y            float64
RcvErr_y         float64
RcvQualTot_y     float64
GamesPlayed_y    float64
Ace               object
Err               object
Srv               object
RcvCount          object
Dig               object
Err.1            float64
Kil              float64
Err.2            float64
Att              float64
RcvErr           float64
RcvQualTot       float64
GamesPlayed      float64
dtype: object

In [24]:
#Convert object dtypes to float
converted_data = final_df[['Ace_x', 'Err_x', 'Srv_x', 'RcvCount_x', 'Dig_x', 'Err.1_x',
       'Kil_x', 'Err.2_x', 'Att_x', 'RcvErr_x', 'RcvQualTot_x',
       'GamesPlayed_x', 'Ace_y', 'Err_y', 'Srv_y', 'RcvCount_y', 'Dig_y',
       'Err.1_y', 'Kil_y', 'Err.2_y', 'Att_y', 'RcvErr_y', 'RcvQualTot_y',
       'GamesPlayed_y', 'Ace', 'Err', 'Srv', 'RcvCount', 'Dig', 'Err.1', 'Kil',
       'Err.2', 'Att', 'RcvErr', 'RcvQualTot', 'GamesPlayed']].astype(float)

In [37]:
Players = final_df['Player']


Aces = final_df['Ace_x']+final_df['Ace_y']+final_df['Ace']
Srv_err = final_df['Err_x']+final_df['Err_y']+final_df['Err']
Total_srv = final_df['Srv_x']+final_df['Srv_y']+final_df['Srv']
RcvCount = final_df['RcvCount_x']+final_df['RcvCount_y']+final_df['RcvCount']
Dig = final_df['Dig_x']+final_df['Dig_y']+final_df['Dig']
Defense_err = final_df['Err.1_x']+final_df['Err.1_y']+final_df['Err.1']
Kills = final_df['Kil_x']+final_df['Kil_y']+final_df['Kil']
Hitting_err = final_df['Err.2_x']+final_df['Err.2_y']+final_df['Err.2']
Att = final_df['Att_x']+final_df['Att_y']+final_df['Att']
Rcv_err = final_df['RcvErr_x']+final_df['RcvErr_y']+final_df['RcvErr']
RcvQualTot = final_df['RcvQualTot_x']+final_df['RcvQualTot_y']+final_df['RcvQualTot']
GamesPlayed = final_df['GamesPlayed_x']+final_df['GamesPlayed_y']+final_df['GamesPlayed']

combined_df = pd.DataFrame({'Players': Players, 'Aces': Aces, 'Srv_err': Srv_err, 'Total_srv': Total_srv, 
                            'RcvCount': RcvCount, 'Rcv_err': Rcv_err, 
                           'RcvQualTot': RcvQualTot, 'Dig': Dig, 'Defense_err': Defense_err, 'Kills': Kills, 
                           'Hitting_err': Hitting_err, 'Att': Att, 'GamesPlayed': GamesPlayed})
combined_df

KeyError: ('Ace_x', 'Ace_y', 'Ace')

In [ ]:
#Add back in other stats. hitting percentage and recieve average

In [ ]:
#summary stats

In [ ]:
#errors in relation to games played

In [ ]:
#questions we want answered
1. who is getting the most sets
2. who has the highest hitting percentage
3. who has the best pass rating
4. who makes the most unforced errors

In [ ]:
#uses
1. college recruiting
2. helps set lineup/offense
3. help determine areas to work on in practice

In [ ]:
#turn into a database